### ISSUE TITLE
Preview Image size

### ISSUE THREAD

**Issue by Mimanolis** [humhub/humhub-modules-linkpreview#37]
Is there a way to enlarge the image in the preview, is it module-based or humhub core-based of how the previews are displayed?

**Comment by samuk** [comment]
![increasesize](https://github.com/user-attachments/assets/bc3c4bc0-29e4-4b72-a421-09a7ebc9122c)

+1 @marc-farre is this one we can fix? cc @luke-

**Comment by marc-farre** [comment]
The saved image is large. It's only a rendering issue.

Currently images are fixed to 80px width:

![image](https://github.com/user-attachments/assets/0c39b172-1a56-44c9-b53c-cb7ee1dc405e)

If we change to 200px it renders this way:

![image](https://github.com/user-attachments/assets/cef00f2b-9182-4e64-81fd-bccf9655ecc9)

I think we should define the width via CSS to handle the many situations (small screen size and portrait format).

@luke- Would you like me to try a PR with CSS instead of this fixed 80px width?

**Comment by luke-** [comment]
@marc-farre Yes please. Thanks!

**Comment by marc-farre** [comment]
@luke- PR https://github.com/humhub/linkpreview/pull/21

With this PR, the image is 30% width of the wall entry width.
And it has a maximum of 150px height (if the height exceeds, the width gets lower to preserve the image ration and keep the 10px space between the image and the text).

Desktop:
![image](https://github.com/user-attachments/assets/f53bae68-4538-4a1f-9367-36bc8c3f8497)

Mobile:
![image](https://github.com/user-attachments/assets/43697781-f9fc-4273-903a-7e84de252944)

**Comment by luke-** [comment]
@marc-farre Thanks, looks good for me! I'll release a new module version now.
