### ISSUE TITLE
Link previews with validation errors are silently discarded

### ISSUE THREAD

**Issue by verement** [humhub/humhub-modules-linkpreview#6]
If a link preview record fails validation, for example because a URL is longer than 255 characters, the preview is silently discarded upon submitting the post.

This can be especially bewildering if the troublesome URL is for the preview image, over which the user has no control.

**Comment by luke-** [comment]
Maybe we should throw a Yii::warning in such cases?

**Comment by yurabakhtin** [comment]
@luke- I cannot understand how this module should work.
When I create a new post with text like `Test http://spotify.com text` I don't see the link is rendered with thumbnail icon as it is displayed on doc page. Should I enable something else to make this module works?

I run `composer install` successfully.
But I can run `npm install` without errors only if remove a comma after `"doc": "docs",` and if remove completely the line `
`"euskadi31/Opengraph": "^1.0.0"`` because it seems the package doesn't exists, I got the error:

```
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "euskadi31/Opengraph": name can only contain URL-friendly characters
```

This is a single package so if we will remove I don't see a reason to keep the `package.json` at all. Please correct me if I am wrong here.

**Comment by luke-** [comment]
@yurabakhtin I fixed the problem with the Composer Json, seems that ComposerV2 had a problem with the capitalization of the package name.

Can you try a composer install again?

**Comment by yurabakhtin** [comment]
@luke- Yes, in my previous comment I forgot to report about the issue in `composer.json`, I fixed that too on my local file without commit yet, but if you did this first then thanks, , so I could install it after the same fix
However as I wrote above the problems exist in the `package.json` and it seems we don't need that at all, can you please check that?

**Comment by luke-** [comment]
@yurabakhtin Yes, I think we can delete the package.json file. Does the module work for you now?

**Comment by yurabakhtin** [comment]
@luke- Yes, the problem was in redirect URL on the server side of the URL, for example, the url `https://www.spotify.com/` redirects me to `https://www.spotify.com/ru-ru/` so I need to use this url to test this module.

**Comment by yurabakhtin** [comment]
@luke- I have implemented to display the validation errors after fetching an URL:

<img width="674" alt="fetch_errors" src="https://user-images.githubusercontent.com/6995524/111998419-08103080-8b2d-11eb-8fcf-9dffba92401a.png">

MR https://git.humhub.org/modules/linkpreview/-/merge_requests/1

**Comment by luke-** [comment]
@yurabakhtin Thanks & Merged
